export default {
  "Video game": "🎮",
  "Black bird": "🐦‍⬛",
  Donkey: "🫏",
  Goose: "🪿",
  Hyacinth: "🪻",
  Jellyfish: "🪼",
  Moose: "🫎",
  Ginger: "🫚",
  "Pea pod": "🫛",
  Flute: "🪈",
  "Folding hand fan": "🪭",
  "Hair pick": "🪮",
  Maracas: "🪇",
  Paperclip: "📎",
  Pinata: "🪅",
  Wireless: "🛜",
  "Grey heart": "🩶",
  "Light blue heart": "🩵",
  "Pink heart": "🩷",
  "Shaking face": "🫨",
  Khanda: "🪯",
};
